apiVersion: v1
kind: Service
metadata:
  name: jaipro-gateway
  namespace: jaipro
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8000
      port: 8080
      nodePort: 31084
  selector:
    service: jaipro-gateway
    type: backend