spring:
  profiles:
    active: dev
  codec:
    max-in-memory-size: 5000KB

server:
  port: 8000

eureka:
  propagate:
    headers:
      - content-type
      - accept
      - x-requested-with
      - authorization
      - request-id
      - service-caller
      - country-origin

  cors:
    address:
      - http://localhost:8080
      - http://localhost:9010
      - http://181.64.90.211:8080
      - http://verdant-cascade-390018.uc.r.appspot.com

